---
# tasks file for osp_director
- name: import secret variable file
  include_vars: "vars/vault"
  no_log: true

- name: set hostname
  hostname:
    name: "{{ undercloud['hostname'] }}"

- name: add line to hosts file for self
  lineinfile:
    dest: /etc/hosts
    state: present
    regexp: '^{{ external_ip }}'
    line: '{{ external_ip }}  {{ fqdn }}  {{ fqdn_short }}'

- sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: register System with RHN Subscription Manager
  redhat_subscription:
    state: present
    username: "{{ rhn_user }}"
    password: "{{ rhn_pwd }}"
    pool: "{{ rhn_pool_name }}"
  when: ansible_distribution == 'RedHat'

- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false

- name: disable all repositories
  command: subscription-manager repos --disable=\*

- name: enable the needed rhel repositories
  command: subscription-manager repos --enable={{ item }}
  with_items: "{{ rhn_repo_channels }}"

- name: add stack user and set password
  user:
    name: stack
    password: "{{ stack_user_pwd }}"

- name: allow stack user to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^stack'
    line: 'stack ALL=(ALL) NOPASSWD:ALL'

- name: turn off requiretty for sudo
  lineinfile:
    dest: /etc/sudoers
    line: "{{ item.line }}"
    state: "{{ item.state }}"
  with_items:
     - { line: "Defaults !requiretty", state: present }
     - { line: "Defaults requiretty", state: absent }

- name: check sudoers
  shell: cat /etc/sudoers | grep tty
  register: sudoers_output

- name: Debug
  debug:
    msg: "Sudoers: {{ sudoers_output }}"

- name: install several useful utility and undercloud packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - 'screen'
    - 'wget'
    - 'vim'
    - 'tree'
    - 'yum-utils'
    - 'facter'
    - 'crudini'
    - 'git'
    - 'libguestfs-tools-c'
    - 'python-tripleoclient'
    - 'rhosp-director-images'
    - 'rhosp-director-images-ipa'

- name: update packages
  yum:
    name: '*'
    state: latest
  register: yum_result
  async: 1000
  poll: 30

- name: check Kernel is the Latest
  shell: if [ $(uname -r) == $(rpm -q kernel | tail -n 1 | sed -e 's/kernel-//g') ] ; then echo no ; else echo reboot; fi
  ignore_errors: true
  register: reboot_hint

- name: make sure cloud-init is not installed
  yum:
    name: cloud-init
    state: absent

- name: restart undercloud machine to get updated kernel
  shell: sleep 2 && shutdown -r now "Ansible Restart Triggered for Undercloud Install"
  async: 1
  poll: 0
  ignore_errors: true
  when: yum_result.changed or reboot_hint.stdout.find("reboot") != -1

- name: waiting for Server to come back
  wait_for:
    host: "{{ inventory_hostname }}"
    state: started
    delay: 10
    connect_timeout: 5
    timeout: 300
    port: 22
  delegate_to: 127.0.0.1
  become: false
  ignore_errors: true

- name: setting provisioning interface onboot=no
  lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ undercloud['local_interface'] }}
    state: present
    regexp: '^ONBOOT'
    line: 'ONBOOT=no'

- name: copy undercloud.conf template
  become: yes
  become_user: stack
  copy:
    src: /usr/share/instack-undercloud/undercloud.conf.sample
    dest: /home/stack/undercloud.conf
    remote_src: true
    owner: stack
    group: stack
    mode: 0644

- name: set undercloud.conf variables in the default section
  become: yes
  become_user: stack
  ini_file:
    dest: /home/stack/undercloud.conf
    section: DEFAULT
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    mode: 0644
    backup: no
  with_items:
    - { key: image_path, value: "{{ undercloud['image_path'] }}" }
    - { key: undercloud_hostname, value: "{{ undercloud['hostname'] }}" }
    - { key: local_ip, value: "{{ undercloud['local_ip'] }}" }
    - { key: undercloud_public_vip, value: "{{ undercloud['public_vip'] }}" }
    - { key: undercloud_admin_vip, value: "{{ undercloud['admin_vip'] }}" }
    - { key: local_interface, value: "{{ undercloud['local_interface'] }}" }
    - { key: generate_service_certificate, value: "{{ undercloud['generate_service_certificate'] }}" }
    - { key: certificate_generate_ca, value: "{{ undercloud['certificate_generation_ca'] }}" }
    - { key: undercloud_service_certificate, value: "{{ undercloud['undercloud_service_certificate'] }}"}
    - { key: service_principal, value: "{{ undercloud['service_principal'] }}"}
    - { key: network_cidr, value: "{{ undercloud['network_cidr'] }}" }
    - { key: network_gateway, value: "{{ undercloud['network_gateway'] }}" }
    - { key: masquerade_network, value: "{{ undercloud['masquerade_network'] }}" }
    - { key: dhcp_start, value: "{{ undercloud['dhcp_start'] }}" }
    - { key: dhcp_end, value: "{{ undercloud['dhcp_end'] }}" }
    - { key: inspection_interface, value: "{{ undercloud['inspection_interface'] }}"}
    - { key: inspection_iprange, value: "{{ undercloud['inspection_start'] }},{{ undercloud['inspection_end'] }}" }
    - { key: inspection_runbench, value: "{{ undercloud['inspection_runbench'] }}"}
    - { key: inspection_enable_uefi, value: "{{ undercloud['inspection_enable_uefi'] }}"}
    - { key: undercloud_debug, value: "{{ undercloud['debug'] }}"}
    - { key: enable_tempest, value: "{{ undercloud['enable_tempest'] }}"}
    - { key: enable_validations, value: "{{ undercloud['enable_validations'] }}"}
    - { key: enable_mistral, value: "{{ undercloud['enable_mistral'] }}"}
    - { key: enable_zaqar, value: "{{ undercloud['enable_zaqar'] }}"}
    - { key: enable_telemetry, value: "{{ undercloud['enable_telemetry'] }}"}
    - { key: enable_ui, value: "{{ undercloud['enable_ui'] }}"}
    - { key: ipxe_enabled, value: "{{ undercloud['ipxe_enabled'] }}"}
    - { key: store_events, value: "{{ undercloud['store_events'] }}" }
    - { key: clean_nodes, value: "{{ undercloud['clean_nodes'] }}"}

- name: set undercloud.conf variables in the auth section
  become: yes
  become_user: stack
  ini_file:
    dest: /home/stack/undercloud.conf
    option: undercloud_admin_password
    section: auth
    value: "{{ undercloud['admin_password'] }}"
    mode: 0644
    backup: no

- name: make images and templates directories
  become: yes
  become_user: stack
  file:
    path: "/home/stack/{{ item }}"
    state: directory
    mode: 0755
    owner: stack
    group: stack
  with_items:
    - 'images'
    - 'templates'

- name: unpacking overcloud and ironic images
  become: yes
  become_user: stack
  unarchive:
    src: "{{ item }}"
    remote_src: true
    dest: /home/stack/images
  with_items:
    - '/usr/share/rhosp-director-images/overcloud-full-latest-10.0.tar'
    - '/usr/share/rhosp-director-images/ironic-python-agent-latest-10.0.tar'

- name: install the Undercloud
  become: yes
  become_user: stack
  shell: openstack undercloud install
  args:
    chdir: /home/stack
  async: 2700
  poll: 30

- name: adding overcloud images to OSPD
  become: yes
  become_user: stack
  shell: source /home/stack/stackrc && openstack overcloud image upload
  args:
    chdir: /home/stack/images

- name: set debug flag to false in DEFAULT section
  ini_file:
    dest: "{{ item }}"
    section: DEFAULT
    option: debug
    value: false
    backup: no
  with_items:
    - '/etc/nova/nova.conf'
    - '/etc/neutron/neutron.conf'
    - '/etc/heat/heat.conf'
    - '/etc/ironic/ironic.conf'

- name: fix ceilometer database ttls
  ini_file:
    dest: /etc/ceilometer/ceilometer.conf
    section: database
    option: "{{ item }}"
    value: 259200
    backup: no
  with_items:
    - 'metering_time_to_live'
    - 'event_time_to_live'

- name: restart openstack services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - 'openstack-*'
    - 'neutron-*'
    - 'httpd'
